import { StyleSheet } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flexGrow: 1,
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.xl,
      paddingBottom: Spacing["5xl"],
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: Spacing.xl,
    },
    backButton: {
      marginRight: Spacing.md,
      padding: Spacing.sm,
    },
    ichTypeSection: {
      marginBottom: Spacing.xl,
    },
    interactionTypeSection: {
      marginBottom: Spacing.xl,
    },
    sceneSection: {
      marginBottom: Spacing.xl,
    },
    sectionLabel: {
      marginBottom: Spacing.md,
    },
    categoryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.sm,
    },
    categoryButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    inputSection: {
      marginBottom: Spacing.xl,
    },
    inputLabel: {
      marginBottom: Spacing.md,
    },
    textInput: {
      minHeight: 100,
      padding: Spacing.lg,
      borderRadius: BorderRadius.lg,
      fontSize: 16,
      lineHeight: 24,
    },
    generateButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing.xl,
      paddingHorizontal: Spacing["2xl"],
      borderRadius: BorderRadius.xl,
      marginBottom: Spacing["2xl"],
      gap: Spacing.sm,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 1,
      shadowRadius: 12,
      elevation: 8,
    },
    generateButtonText: {},
    customizeButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: Spacing.xl,
      paddingHorizontal: Spacing["2xl"],
      borderRadius: BorderRadius.xl,
      marginBottom: Spacing["2xl"],
      gap: Spacing.sm,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 1,
      shadowRadius: 12,
      elevation: 8,
    },
    customizeButtonText: {},
    resultsSection: {
      gap: Spacing.md,
    },
    resultsTitle: {
      marginBottom: Spacing.sm,
    },
    resultCard: {
      padding: Spacing.lg,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundDefault,
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 1,
      shadowRadius: 8,
      elevation: 4,
    },
    resultHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: Spacing.md,
    },
    resultHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    resultCategory: {},
    favoriteButton: {
      padding: Spacing.xs,
    },
    resultImage: {
      width: '100%',
      height: 200,
      borderRadius: BorderRadius.lg,
      resizeMode: 'cover',
      marginBottom: Spacing.md,
    },
    resultImagesContainer: {
      flexDirection: 'column',
      gap: Spacing.md,
    },
    resultSubImages: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    resultSubImage: {
      flex: 1,
      height: 100,
      borderRadius: BorderRadius.lg,
      resizeMode: 'cover',
    },
    resultActions: {
      flexDirection: 'row',
      gap: Spacing.sm,
      marginTop: Spacing.md,
    },
    actionButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
    },
    actionButtonText: {
      fontSize: 12,
    },
    previewPlaceholder: {
      height: 200,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      justifyContent: 'center',
      alignItems: 'center',
      gap: Spacing.sm,
      marginBottom: Spacing.md,
    },
    metadata: {
      padding: Spacing.sm,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      backgroundColor: theme.backgroundRoot,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: '80%',
      overflow: 'hidden',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: Spacing.xl,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    modalBody: {
      padding: Spacing.lg,
      maxHeight: 400,
    },
    modalFooter: {
      flexDirection: 'row',
      gap: Spacing.md,
      padding: Spacing.xl,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    modalButton: {
      flex: 1,
      paddingVertical: Spacing.lg,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
    },
    modalButtonCancel: {
      backgroundColor: theme.backgroundTertiary,
    },
    modalButtonConfirm: {
      backgroundColor: theme.primary,
    },
    modalButtonDisabled: {
      opacity: 0.5,
    },
    loadingContainer: {
      paddingVertical: Spacing["2xl"],
      alignItems: 'center',
      gap: Spacing.md,
    },
    loadingText: {},
    emptyContainer: {
      paddingVertical: Spacing["3xl"],
      alignItems: 'center',
      gap: Spacing.md,
    },
    emptyText: {},
    materialItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: Spacing.md,
      borderRadius: BorderRadius.lg,
      marginBottom: Spacing.md,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 2,
      borderColor: 'transparent',
    },
    materialItemSelected: {
      borderColor: theme.primary,
    },
    materialItemImage: {
      width: 60,
      height: 60,
      borderRadius: BorderRadius.lg,
      resizeMode: 'cover',
    },
    materialItemVideo: {
      width: 60,
      height: 60,
      borderRadius: BorderRadius.lg,
      overflow: 'hidden',
    },
    materialPlayIcon: {
      position: 'absolute',
      top: 18,
      left: 18,
    },
    materialItemPlaceholder: {
      width: 60,
      height: 60,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    materialItemInfo: {
      flex: 1,
      marginLeft: Spacing.md,
    },
    materialSection: {
      marginBottom: Spacing.xl,
    },
    materialButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
      paddingVertical: Spacing.lg,
      paddingHorizontal: Spacing.xl,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1,
      borderColor: theme.borderLight,
      position: 'relative',
    },
    materialButtonText: {
      flex: 1,
    },
    selectedMaterialIndicator: {
      position: 'absolute',
      top: Spacing.sm,
      right: Spacing.sm,
    },
    selectedMaterialCard: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: Spacing.md,
      borderRadius: BorderRadius.lg,
      marginTop: Spacing.md,
      backgroundColor: theme.backgroundDefault,
    },
    selectedMaterialImage: {
      width: 50,
      height: 50,
      borderRadius: BorderRadius.lg,
      resizeMode: 'cover',
    },
    selectedMaterialInfo: {
      flex: 1,
      marginLeft: Spacing.md,
    },
    customizeImageContainer: {
      marginBottom: Spacing.lg,
    },
    customizeImage: {
      width: '100%',
      height: 200,
      borderRadius: BorderRadius.xl,
      resizeMode: 'cover',
    },
    formGroup: {
      marginBottom: Spacing.lg,
      padding: Spacing.lg,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundDefault,
    },
    formLabel: {
      marginBottom: Spacing.sm,
    },
    formInput: {
      minHeight: 48,
      padding: Spacing.md,
      borderRadius: BorderRadius.lg,
      fontSize: 16,
      borderWidth: 1,
      borderColor: theme.borderLight,
    },
    formInputMultiline: {
      minHeight: 100,
    },
    selectedImageContainer: {
      position: 'relative',
    },
    selectedImage: {
      width: '100%',
      height: 200,
      borderRadius: BorderRadius.xl,
      resizeMode: 'cover',
    },
    changeImageButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      position: 'absolute',
      bottom: Spacing.md,
      right: Spacing.md,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.lg,
      borderRadius: BorderRadius.lg,
      backgroundColor: 'rgba(255, 255, 255, 0.9)',
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.5,
      shadowRadius: 4,
      elevation: 4,
    },
    imagePlaceholder: {
      height: 200,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundTertiary,
      justifyContent: 'center',
      alignItems: 'center',
      gap: Spacing.sm,
      borderWidth: 2,
      borderColor: theme.borderLight,
      borderStyle: 'dashed',
    },
    imageGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.md,
    },
    imageItem: {
      width: '48%',
      aspectRatio: 1,
      position: 'relative',
      borderRadius: BorderRadius.xl,
      overflow: 'hidden',
    },
    imageItemImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    imageItemSelectedOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      justifyContent: 'center',
      alignItems: 'center',
    },
  });
};
